### ISSUE TITLE
Cannot read property 'BaseInputElement' of undefined

### ISSUE THREAD

**Issue by devflorez** [cometchat-pro/cometchat-pro-react-native-ui-kit#63]
Hello CometChat Team,

I am encountering an issue with the integration of your SDK. As soon as I execute the following initialization code in my React Native app:

CometChatUIKit.init({
  appId: cometChatConfig.cometChatAppId,
  authKey: cometChatConfig.cometChatAuthKey,
  region: cometChatConfig.cometChatRegion,
});
I receive the following error: TypeError: Cannot read property 'BaseInputElement' of undefined, js engine:

I'm trying to integrate the CometChat SDK at the startup of my app, and I am using the following dependencies:

"expo": "~50.0.14"
"react": "18.2.0"
"react-native": "0.73.6"
"@cometchat/calls-sdk-react-native": "^4.0.4"
"@cometchat/chat-sdk-react-native": "^4.0.5"
"@cometchat/chat-uikit-react-native": "^4.2.2"
"@react-native-community/clipboard": "^1.5.1"
"@react-native-community/datetimepicker": "^7.6.3"
"@react-native-community/netinfo": "11.1.0"
"react-native-background-timer": "^2.4.1"
"react-native-callstats": "^3.73.22"
I want to emphasize that I am not using Expo Go for this setup.

Could you please assist me in resolving this error?

Best regards.

**Comment by devflorez** [comment]
Hello Keagan,

Thank you for your assistance.

I am integrating with Expo, but not using Expo Go. Here's the error I encounter:

ERROR TypeError: Cannot read property 'BaseInputElement' of undefined, js engine: hermes
ERROR Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes


This issue occurs when I initialize with the following code:

import { CometChatUIKit, CometChatContextProvider, CometChatTheme } from "@cometchat/chat-uikit-react-native";

useEffect(() => {
  CometChatUIKit.init({
    appId: cometChatConfig.cometChatAppId,
    authKey: cometChatConfig.cometChatAuthKey,
    region: cometChatConfig.cometChatRegion,
  })
  .then(() => {
    console.log("CometChat UIKit initialized successfully");
  })
  .catch(() => {
    console.log("CometChat UIKit initialization failed");
  });
}, []);



Removing this initialization, my app runs perfectly. However, adding it triggers the error. It's worth mentioning that I haven't imported any other UI component into any screen; just importing and initializing causes the error.

Regards.

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-20 at 17 06 02](https://github.com/cometchat/cometchat-uikit-react-native/assets/69540787/cce8f7ff-eef4-461a-add7-33034326fd33)

**Comment by coyksdev** [comment]
Hi @devflorez, did you fix it?

**Comment by coyksdev** [comment]
It looks like there is no **InteractiveData** files in the **/lib**. Which are being called by CallingExtentionDecorator.tsx

/src
<img src="https://github.com/cometchat/cometchat-uikit-react-native/assets/19565694/1c58574b-b90c-47bd-afc7-c0fadde9ff4e" width=300 />

/lib
<img src="https://github.com/cometchat/cometchat-uikit-react-native/assets/19565694/194e46d1-90b5-4a2f-9590-33c53b3a1140" width=300/>

**Comment by allenhark** [comment]
Hello, any updates on fixing this issue. Am getting the same problem, thus our development has come to a halt.

**Comment by jeliel-augusto20** [comment]
Hello, we also having the same issue

**Comment by coyksdev** [comment]
Same here. We are still waiting.

**Comment by coyksdev** [comment]
it is working now. thank you so much!
