### ISSUE TITLE
CometChatConversationsWithMessages Component

### ISSUE THREAD

**Issue by idoMadarr** [cometchat-pro/cometchat-pro-react-native-ui-kit#73]
Hello,

I am facing a strange issue with the CometChatConversationsWithMessages component. It does not display text messages, but this happens ONLY in the first time I run  my react native (cli) app. After restarting the app once, everything works fine. **The result is that I am getting the messages in real time, but with no text...** 

Since this is a built-in component, I’m not sure if there’s much I can do about it. I would greatly appreciate any help or guidance regarding this issue. 

(Could it be that this behavior occurs only on the free plan?)

Thank!

"react-native": "0.75.4",

![Simulator Screenshot - iPhone 16 Pro - 2024-12-14 at 16 57 33](https://github.com/user-attachments/assets/19e6eccf-5a00-4b1c-9c6b-a9b9f556820e)

**Comment by idoMadarr** [comment]
FIXED! 

The strange behavior was due to a mismatch between the CometChat SDK and the UI Kit on my side.

Although this issue occurred because of incorrect implementation, I believe it's worth being aware of. The problem arose because I implemented the UI Kit but attempted to log in using the login method from the SDK library.

Specifically, I used CometChat.login() instead of CometChatUIKit.login().

As a result, users experience a bug where their messages (including their own) appear with no content the first time they log in.

**Comment by Afroz-Cometchat** [comment]
Hi,

Thank you for the update and for identifying the issue. In case of using UI Kits, it is necessary to initialize and log in using CometChatUIKit instead of CometChat. The CometChatUIKit methods internally use the SDK methods along with additional code to support UI Kits, ensuring proper functionality.

If you have further questions or suggestions, feel free to share.
